services:
  - type: web
    name: splitwise-clone
    env: docker
    plan: free
    image:
      url: ghcr.io/scalolli/splitwise-clone:latest
    envVars:
      - key: JDBC_URL
        fromDatabase:
          name: splitwise-db
          property: connectionString
      - key: DB_USERNAME
        fromDatabase:
          name: splitwise-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: splitwise-db
          property: password
      - key: SESSION_SECRET
        generateValue: true

databases:
  - name: splitwise-db
    plan: free
